name: defakeit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^9.1.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.3
  equatable: ^2.0.5
  record: ^6.0.0
  percent_indicator: ^4.2.2
  http: ^1.3.0
  http_parser: ^4.0.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  mime: ^1.0.4
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

  # إعدادات الترجمة
  generate: true